name: socket_io_plus
description: >
  Port of JS/Node library Socket.io. It enables real-time, bidirectional and 
  event-based communication cross-platform. Dart 3 compatible fork.
version: 2.0.0
homepage: https://pub.dev/packages/socket_io_plus

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  stream: ^4.0.0
  socket_io_common: ^3.0.0
  uuid: ^4.0.0
  logging: ^1.0.0
dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0
